# Generated by Django 4.2 on 2024-08-10 19:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_code', models.CharField(max_length=32, unique=True)),
                ('dis_type', models.CharField(choices=[('percentage', 'Percentage'), ('value', 'Value')], default='Percentage', max_length=15)),
                ('dis_amount', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('redeemed', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاها',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('discription', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='website.categories')),
                ('dicount', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='website.discounts')),
                ('market', models.ManyToManyField(related_name='product', to='website.markets')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMarkets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='website.markets')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market', to='accounts.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('customer', models.ForeignKey(default='not found', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rating', to='accounts.customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='website.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/product/default.jpg', upload_to='images/product/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='website.products')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('customer', models.ForeignKey(default='not found', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comment', to='accounts.customers')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.comments')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='website.products')),
            ],
        ),
    ]
