# Generated by Django 4.2 on 2024-08-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_categories_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
