# Generated by Django 4.2 on 2024-08-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_productimages_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='dis_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('value', 'Value')], default='percentage', max_length=15),
        ),
    ]
