# Generated by Django 5.0 on 2024-08-26 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_discounts_dis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='markets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markets',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
