# Generated by Django 5.0 on 2024-08-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_markets_created_at_markets_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markets',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='markets',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
