# Generated by Django 4.2 on 2024-08-27 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_markets_created_at_alter_markets_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
