# Generated by Django 4.2 on 2024-09-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_products_created_at_products_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='discounts',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='markets',
            options={'verbose_name': 'Market', 'verbose_name_plural': 'Markets'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
    ]
