# Generated by Django 4.2 on 2024-09-03 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_discounts_dis_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='dis_code',
            field=models.UUIDField(default=uuid.UUID('eedeabc2-e567-4731-91cf-6fb2b306032d'), unique=True),
        ),
    ]
