# Generated by Django 4.2 on 2024-09-03 07:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customeraddress_options_and_more'),
        ('website', '0013_alter_discounts_dis_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applied_discount', to='accounts.staffs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discounts',
            name='applied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='redeemed_discount', to='accounts.customers'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='dis_code',
            field=models.UUIDField(default=uuid.UUID('39e4c767-ab54-4f7b-930a-da32eb6fbbac'), unique=True),
        ),
    ]
