# Generated by Django 4.2 on 2024-09-03 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customeraddress_options_and_more'),
        ('website', '0014_discounts_created_by_alter_discounts_applied_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='applied_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='redeemed_discount', to='accounts.customers'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='dis_code',
            field=models.UUIDField(default=uuid.UUID('6e6cbaa0-ec2e-4b7a-9f32-472edd6f2482'), unique=True),
        ),
    ]
