# Generated by Django 4.2 on 2024-09-03 12:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customeraddress_options_and_more'),
        ('website', '0015_alter_discounts_applied_by_alter_discounts_dis_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='applied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='redeemed_discount', to='accounts.customers'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='dis_code',
            field=models.UUIDField(default=uuid.UUID('fded0a75-b9f0-44b6-ada3-4de53259132f'), unique=True),
        ),
    ]
