# Generated by Django 4.2 on 2024-09-03 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_discounts_applied_by_alter_discounts_dis_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='dis_code',
            field=models.UUIDField(default=uuid.UUID('4d7e1897-f486-4f96-b3ca-0a53f69fa8ff'), unique=True),
        ),
    ]
