# Generated by Django 4.2 on 2024-09-03 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customeraddress_options_and_more'),
        ('website', '0017_alter_discounts_dis_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='redeemed_discount', to='accounts.customers'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='dis_code',
            field=models.UUIDField(default=uuid.UUID('bfcdd59c-79dc-49fe-9a1f-be20dc27736c'), unique=True),
        ),
    ]
