# Generated by Django 4.2 on 2024-09-03 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customeraddress_options_and_more'),
        ('website', '0018_alter_discounts_applied_by_alter_discounts_dis_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='applied_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='redeemed_discount', to='accounts.customers'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='dis_code',
            field=models.UUIDField(default=uuid.UUID('297a0fbf-02ce-4d09-80f3-907ed9da2b64'), unique=True),
        ),
    ]
