# Generated by Django 4.2 on 2024-09-04 12:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_discounts_applied_by_alter_discounts_dis_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='dis_code',
            field=models.UUIDField(default=uuid.UUID('a6d9aa3e-e2a6-4b1d-938c-4c765379a1ff'), unique=True),
        ),
        migrations.AlterField(
            model_name='markets',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='markets',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
