# Generated by Django 4.2 on 2024-09-04 12:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_discounts_dis_code_alter_markets_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='dis_code',
            field=models.UUIDField(default=uuid.UUID('491fe92b-bdc5-4c98-afb5-c11b1eab8dbb'), unique=True),
        ),
        migrations.AlterField(
            model_name='markets',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='markets',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
