# Generated by Django 4.2 on 2024-08-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_customer_carts_customer_carts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='discount',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='total_discount',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipment_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Processing', max_length=20),
        ),
    ]
