# Generated by Django 4.2 on 2024-08-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_orderdetails_discount_orders_total_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
