# Generated by Django 4.2 on 2024-09-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_orders_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdetails',
            options={'verbose_name': 'Cart Detail', 'verbose_name_plural': 'Cart Details'},
        ),
        migrations.AlterModelOptions(
            name='carts',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'Order Detail', 'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
