# Generated by Django 4.2 on 2024-09-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name': 'Customer Address', 'verbose_name_plural': 'Customers Address'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='staffs',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
    ]
